/*
 * AM335x Power domains framework
 *
 * This file is automatically generated from the AM335X hardware databases.
 *
 * Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#include <linux/kernel.h>
#include <linux/init.h>

#include "powerdomain.h"
#include "prcm-common.h"
#include "prm335x.h"


/* gfx_335x_pwrdm:  */
static struct powerdomain gfx_335X_pwrdm = {
	.name		  = "gfx_pwrdm",
	.prcm_offs	  = AM335X_PRM_GFX_MOD,
	.omap_chip	  = OMAP_CHIP_INIT(CHIP_IS_AM335X),
	.pwrsts		  = PWRSTS_OFF_RET_ON,
	.pwrsts_logic_ret = PWRSTS_OFF_RET,
	.banks		  = 1,
	.pwrsts_mem_ret	= {
		[0] = PWRSTS_OFF_RET,	/* gfx_mem */
	},
	.pwrsts_mem_on	= {
		[0] = PWRDM_POWER_ON,	/* gfx_mem */
	},
};

/* rtc_335x_pwrdm: TBD */
static struct powerdomain rtc_335X_pwrdm = {
	.name		  = "rtc_pwrdm",
	.prcm_offs	  = AM335X_PRM_RTC_MOD,
	.omap_chip	  = OMAP_CHIP_INIT(CHIP_IS_AM335X),
	.pwrsts		  = PWRDM_POWER_ON,
	.pwrsts_logic_ret = PWRSTS_OFF_RET,
};

/* wkup_335x_pwrdm: TBD */
static struct powerdomain wkup_335X_pwrdm = {
	.name		  = "wkup_pwrdm",
	.prcm_offs	  = AM335X_PRM_WKUP_MOD,
	.omap_chip	  = OMAP_CHIP_INIT(CHIP_IS_AM335X),
	.pwrsts		  = PWRDM_POWER_ON,
	.pwrsts_logic_ret = PWRSTS_OFF_RET,
	.banks		  = 1,
	.pwrsts_mem_ret	= {
		[0] = PWRDM_POWER_OFF,	/* debugss_mem */
	},
	.pwrsts_mem_on	= {
		[0] = PWRDM_POWER_ON,	/* debugss_mem */
	},
};

/* per_335x_pwrdm: TBD */
static struct powerdomain per_335X_pwrdm = {
	.name		  = "per_pwrdm",
	.prcm_offs	  = AM335X_PRM_PER_MOD,
	.omap_chip	  = OMAP_CHIP_INIT(CHIP_IS_AM335X),
	.pwrsts		  = PWRSTS_OFF_RET_ON,
	.pwrsts_logic_ret = PWRSTS_OFF_RET,
	.banks		  = 3,
	.pwrsts_mem_ret	= {
		[0] = PWRSTS_OFF_RET,	/* icss_mem */
		[1] = PWRSTS_OFF_RET,	/* per_mem */
		[2] = PWRSTS_OFF_RET,	/* ram_mem */
	},
	.pwrsts_mem_on	= {
		[0] = PWRSTS_OFF_RET,	/* icss_mem */
		[1] = PWRDM_POWER_ON,	/* per_mem */
		[2] = PWRSTS_OFF_RET,	/* ram_mem */
	},
};

/* mpu_335x_pwrdm: TBD */
static struct powerdomain mpu_335X_pwrdm = {
	.name		  = "mpu_pwrdm",
	.prcm_offs	  = AM335X_PRM_MPU_MOD,
	.omap_chip	  = OMAP_CHIP_INIT(CHIP_IS_AM335X),
	.pwrsts		  = PWRSTS_OFF_RET_ON,
	.pwrsts_logic_ret = PWRSTS_OFF_RET,
	.banks		  = 3,
	.pwrsts_mem_ret	= {
		[0] = PWRSTS_OFF_RET,	/* mpu_l1 */
		[1] = PWRSTS_OFF_RET,	/* mpu_l2 */
		[2] = PWRSTS_OFF_RET,	/* mpu_ram */
	},
	.pwrsts_mem_on	= {
		[0] = PWRDM_POWER_ON,	/* mpu_l1 */
		[1] = PWRDM_POWER_ON,	/* mpu_l2 */
		[2] = PWRDM_POWER_ON,	/* mpu_ram */
	},
};

/* cefuse_335x_pwrdm:  */
static struct powerdomain cefuse_335X_pwrdm = {
	.name		  = "cefuse_pwrdm",
	.prcm_offs	  = AM335X_PRM_CEFUSE_MOD,
	.omap_chip	  = OMAP_CHIP_INIT(CHIP_IS_AM335X),
	.pwrsts		  = PWRSTS_OFF_ON,
};

/*
 * The following power domains are not under SW control
 *
 * stdefuse
 */

static struct powerdomain *powerdomains_am335x[] __initdata = {
	&gfx_335X_pwrdm,
	&rtc_335X_pwrdm,
	&wkup_335X_pwrdm,
	&per_335X_pwrdm,
	&mpu_335X_pwrdm,
	&cefuse_335X_pwrdm,
	NULL
};

void __init am335x_powerdomains_init(void)
{
	pwrdm_init(powerdomains_am335x, &am335x_pwrdm_operations);
}

